export interface Language {
    code: string; // ISO 639-1 code
    name: string;
  }
  
  export interface Country {
    code: string; // ISO 3166-1 alpha-2 code
    name: string;
  }
  
  /**
   * @constant LANGUAGES
   * @description Top 100 languages by total number of speakers, with ISO 639-1 codes.
   */
  export const LANGUAGES: Language[] = [
    { code: 'zh', name: 'Chinese' },
    { code: 'es', name: 'Spanish' },
    { code: 'en', name: 'English' },
    { code: 'hi', name: 'Hindi' },
    { code: 'ar', name: 'Arabic' },
    { code: 'bn', name: 'Bengali' },
    { code: 'pt', name: 'Portuguese' },
    { code: 'ja', name: 'Japanese' },
    { code: 'pa', name: 'Punjabi' },
    { code: 'de', name: 'German' },
    { code: 'jv', name: 'Javanese' },
    { code: 'ko', name: 'Korean' },
    { code: 'fr', name: 'French' },
    { code: 'te', name: 'Telugu' },
    { code: 'mr', name: 'Marathi' },
    { code: 'tr', name: 'Turkish' },
    { code: 'ta', name: 'Tamil' },
    { code: 'ur', name: 'Urdu' },
    { code: 'gu', name: 'Gujarati' },
    { code: 'ms', name: 'Malay' },
    { code: 'kk', name: 'Kazakh' },
    { code: 'fa', name: 'Persian' },
    { code: 'uk', name: 'Ukrainian' },
    { code: 'it', name: 'Italian' },
    { code: 'pl', name: 'Polish' },
    { code: 'ro', name: 'Romanian' },
    { code: 'nl', name: 'Dutch' },
    { code: 'el', name: 'Greek' },
    { code: 'hu', name: 'Hungarian' },
    { code: 'sv', name: 'Swedish' },
    { code: 'he', name: 'Hebrew' },
    { code: 'id', name: 'Indonesian' },
    { code: 'th', name: 'Thai' },
    { code: 'vi', name: 'Vietnamese' },
    { code: 'ml', name: 'Malayalam' },
    { code: 'kn', name: 'Kannada' },
    { code: 'or', name: 'Odia' },
    { code: 'am', name: 'Amharic' },
    { code: 'su', name: 'Sundanese' },
    { code: 'sn', name: 'Shona' },
    { code: 'yo', name: 'Yoruba' },
    { code: 'zu', name: 'Zulu' },
    { code: 'ig', name: 'Igbo' },
    { code: 'cs', name: 'Czech' },
    { code: 'fi', name: 'Finnish' },
    { code: 'da', name: 'Danish' },
    { code: 'no', name: 'Norwegian' },
    { code: 'sk', name: 'Slovak' },
    { code: 'bg', name: 'Bulgarian' },
    { code: 'sr', name: 'Serbian' },
    { code: 'hr', name: 'Croatian' },
    { code: 'lt', name: 'Lithuanian' },
    { code: 'lv', name: 'Latvian' },
    { code: 'sl', name: 'Slovenian' },
    { code: 'et', name: 'Estonian' },
    { code: 'mt', name: 'Maltese' },
    { code: 'is', name: 'Icelandic' },
    { code: 'ga', name: 'Irish' },
    { code: 'cy', name: 'Welsh' },
    { code: 'af', name: 'Afrikaans' },
    { code: 'sw', name: 'Swahili' },
    { code: 'uz', name: 'Uzbek' },
    { code: 'mn', name: 'Mongolian' },
    { code: 'ne', name: 'Nepali' },
    { code: 'si', name: 'Sinhala' },
    { code: 'my', name: 'Burmese' },
    { code: 'lo', name: 'Lao' },
    { code: 'km', name: 'Khmer' },
    { code: 'as', name: 'Assamese' },
  ];
  
  /**
   * @constant COUNTRIES
   * @description Top 100 countries by population, with ISO 3166-1 alpha-2 codes.
   */
  export const COUNTRIES: Country[] = [
    { code: 'CN', name: 'China' },
    { code: 'IN', name: 'India' },
    { code: 'US', name: 'United States' },
    { code: 'ID', name: 'Indonesia' },
    { code: 'PK', name: 'Pakistan' },
    { code: 'NG', name: 'Nigeria' },
    { code: 'BR', name: 'Brazil' },
    { code: 'BD', name: 'Bangladesh' },
    { code: 'MX', name: 'Mexico' },
    { code: 'JP', name: 'Japan' },
    { code: 'ET', name: 'Ethiopia' },
    { code: 'PH', name: 'Philippines' },
    { code: 'EG', name: 'Egypt' },
    { code: 'VN', name: 'Vietnam' },
    { code: 'CD', name: 'DR Congo' },
    { code: 'TR', name: 'Turkey' },
    { code: 'IR', name: 'Iran' },
    { code: 'DE', name: 'Germany' },
    { code: 'TH', name: 'Thailand' },
    { code: 'GB', name: 'United Kingdom' },
    { code: 'FR', name: 'France' },
    { code: 'IT', name: 'Italy' },
    { code: 'TZ', name: 'Tanzania' },
    { code: 'ZA', name: 'South Africa' },
    { code: 'MM', name: 'Myanmar' },
    { code: 'KE', name: 'Kenya' },
    { code: 'KR', name: 'South Korea' },
    { code: 'CO', name: 'Colombia' },
    { code: 'ES', name: 'Spain' },
    { code: 'AR', name: 'Argentina' },
    { code: 'DZ', name: 'Algeria' },
    { code: 'SD', name: 'Sudan' },
    { code: 'UA', name: 'Ukraine' },
    { code: 'UG', name: 'Uganda' },
    { code: 'IQ', name: 'Iraq' },
    { code: 'PL', name: 'Poland' },
    { code: 'CA', name: 'Canada' },
    { code: 'MA', name: 'Morocco' },
    { code: 'SA', name: 'Saudi Arabia' },
    { code: 'UZ', name: 'Uzbekistan' },
    { code: 'PE', name: 'Peru' },
    { code: 'AO', name: 'Angola' },
    { code: 'MY', name: 'Malaysia' },
    { code: 'MZ', name: 'Mozambique' },
    { code: 'GH', name: 'Ghana' },
    { code: 'YE', name: 'Yemen' },
    { code: 'NP', name: 'Nepal' },
    { code: 'VE', name: 'Venezuela' },
    { code: 'MG', name: 'Madagascar' },
    { code: 'CM', name: 'Cameroon' },
    { code: 'CI', name: 'Côte d\'Ivoire' },
    { code: 'KP', name: 'North Korea' },
    { code: 'AU', name: 'Australia' },
    { code: 'NE', name: 'Niger' },
    { code: 'LK', name: 'Sri Lanka' },
    { code: 'BF', name: 'Burkina Faso' },
    { code: 'ML', name: 'Mali' },
    { code: 'RO', name: 'Romania' },
    { code: 'MW', name: 'Malawi' },
    { code: 'CL', name: 'Chile' },
    { code: 'KZ', name: 'Kazakhstan' },
    { code: 'ZM', name: 'Zambia' },
    { code: 'GT', name: 'Guatemala' },
    { code: 'EC', name: 'Ecuador' },
    { code: 'SY', name: 'Syria' },
    { code: 'NL', name: 'Netherlands' },
    { code: 'SN', name: 'Senegal' },
    { code: 'KH', name: 'Cambodia' },
    { code: 'TD', name: 'Chad' },
    { code: 'SO', name: 'Somalia' },
    { code: 'ZW', name: 'Zimbabwe' },
    { code: 'GN', name: 'Guinea' },
    { code: 'RW', name: 'Rwanda' },
    { code: 'BJ', name: 'Benin' },
    { code: 'BI', name: 'Burundi' },
    { code: 'TN', name: 'Tunisia' },
    { code: 'BO', name: 'Bolivia' },
    { code: 'BE', name: 'Belgium' },
    { code: 'HT', name: 'Haiti' },
    { code: 'CU', name: 'Cuba' },
    { code: 'SS', name: 'South Sudan' },
    { code: 'DO', name: 'Dominican Republic' },
    { code: 'CZ', name: 'Czech Republic' },
    { code: 'GR', name: 'Greece' },
    { code: 'JO', name: 'Jordan' },
    { code: 'PT', name: 'Portugal' },
    { code: 'AZ', name: 'Azerbaijan' },
    { code: 'SE', name: 'Sweden' },
    { code: 'HN', name: 'Honduras' },
    { code: 'AE', name: 'United Arab Emirates' },
    { code: 'HU', name: 'Hungary' },
    { code: 'TJ', name: 'Tajikistan' },
    { code: 'BY', name: 'Belarus' },
    { code: 'AT', name: 'Austria' },
    { code: 'PG', name: 'Papua New Guinea' },
    { code: 'RS', name: 'Serbia' },
    { code: 'IL', name: 'Israel' },
    { code: 'CH', name: 'Switzerland' },
    { code: 'TG', name: 'Togo' },
    { code: 'SL', name: 'Sierra Leone' },
    { code: 'HK', name: 'Hong Kong' },
    { code: 'LA', name: 'Laos' },
    { code: 'PY', name: 'Paraguay' },
  ];
  